### ISSUE TITLE
Incorrect conversion of animated images to non-animated formats

### ISSUE THREAD

**Issue by olivervogel** [Intervention/image-driver-vips#13]
If animated images (e.g. GIF) are saved in non-animated formats (e.g. Jpeg), all frames appear in a strip below each other. 

The result is Jpeg but the expected behaviour would be that only the first frame is transferred to the new format.

## Code Example

```php
use Intervention\Image\Drivers\Vips\Driver as VipsDriver;

$image = ImageManager::withDriver(VipsDriver::class)
    ->read('animation.gif')
    ->toJpeg();
```

## Input Image (Animated GIF)

![animation](https://github.com/user-attachments/assets/2f20a84f-ac07-44e6-8eef-c00d42f1219f)

## Output Image (Jpeg)

![localhost](https://github.com/user-attachments/assets/2fd33846-ad4b-4ef2-afc5-488b702a1022)

**Comment by deluxetom** [comment]
@olivervogel I think we could update the `vips` core so frames are broken down into pages (Collection)
https://github.com/libvips/php-vips/issues/116#issuecomment-793940189
Similar to how the `gd` core handles frames

otherwise, we can easily update the encoders to check if the image is animated and only use the first frame, probably an easier fix for now

**Comment by olivervogel** [comment]
@deluxetom I think it's better if the core object only contains a single vips image and only splits it when necessary (or desired).

Your second idea sounds good, although I can imagine that there is an easier way with vips, but I'm not sure.
